data:
  dataset: "SnakeCLEF2021_min-train_metadata_PROD.csv"
  classes: 50
  img_presize: 850 # size to be before resizing next.
  img_size: 800 # size to be after resizing.
dls:
  batch_size: 16
train:
  get_y: binomial
  arch: "convnext_tiny"
  freeze_epochs: 1
  epochs: 10
  lr: 0.001
  wd: 0.2

lr_find: False
track: False
track_name: ${train.epochs}-${train.arch}-size_${data.img_size}_${data.classes}cls
project: "the-snake-project-cls"

load: prog_resize/800_convnext_tiny_50cls_11ep
save: False
export: 800_convnext_tiny_50cls_11ep

defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
