data:
  dataset: "SnakeCLEF2021_min-train_metadata_PROD.csv"
  sample: 10
  pre_size: 128
  img_size: 224
dls:
  batch_size: 64
train:
  get_y: genus
  arch: "resnet18"
  presize_epochs: 5
  epochs: 10
  lr: 0.001

lr_find: False
track: True
name: ${train.arch}
project: "the-snake-project-cls"
save_model: False
cpt_name: ${name}

defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
