data:
  dataset: "SnakeCLEF2021_min-train_metadata_PROD.csv"
  classes: 10
  img_size: 224
dls:
  batch_size: 64
train:
  get_y: genus
  arch: "convnext_tiny"
  freeze_epochs: 1
  epochs: 10
  lr: 0.001
  wd: 0.0

load_learner: None
lr_find: False
track: True
name: ${train.arch}
project: "the-snake-project-cls"
save_model: False
cpt_name: ${name}

defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
